package com.davidread.habittracker.common.ui.theme

import androidx.compose.ui.graphics.Color

object Color {
    val GreenPrimary = Color(0xFF2E7D32)
    val AmberSecondary = Color(0xFFFFC107)
    val TealTertiary = Color(0xFF009688)
    val LightGrayBackground = Color(0xFFF5F5F5)
    val DarkGrayBackground = Color(0xFF121212)
    val DarkGraySurface = Color(0xFF1E1E1E)
    val LightSurfaceVariant = Color(0xFFE8EDE8)
    val LightOnSurfaceVariant = Color(0xFF424942)
    val LightOutline = Color(0xFF727970)
    val LightOutlineVariant = Color(0xFFC2C9C1)
    val LightInverseSurface = Color(0xFF2F312F)
    val LightInverseOnSurface = Color(0xFFF1F1EE)
    val DarkSurfaceVariant = Color(0xFF404941)
    val DarkOnSurfaceVariant = Color(0xFFC2C9C1)
    val DarkOutline = Color(0xFF8C938A)
    val DarkOutlineVariant = Color(0xFF404941)
    val DarkInverseSurface = Color(0xFFE2E3DF)
    val DarkInverseOnSurface = Color(0xFF2F312F)
    val White = Color(0xFFFFFFFF)
    val Black = Color(0xFF000000)
    val RedError = Color(0xFFB00020)
    val RedErrorDark = Color(0xFFF2B8B5)
    val StreakAccent = Color(0xFFFF5722)
    val StreakAccentDark = Color(0xFFFFAB91)
    val SwipeDeleteContainer = Color(0xFFFFDAD6)
    val SwipeDeleteContent = Color(0xFFB3261E)
    val SwipeDeleteContainerDark = Color(0xFF8C1D18)
    val SwipeDeleteContentDark = Color(0xFFFFDAD6)
    val SwipeRenameContainer = Color(0xFFDCEBFF)
    val SwipeRenameContent = Color(0xFF0D47A1)
    val SwipeRenameContainerDark = Color(0xFF0F3B7A)
    val SwipeRenameContentDark = Color(0xFFDCEBFF)
    val SwipeCheckInContainer = Color(0xFFFFE0B2)
    val SwipeCheckInContent = Color(0xFFBF360C)
    val SwipeCheckInContainerDark = Color(0xFF8A3D00)
    val SwipeCheckInContentDark = Color(0xFFFFE0B2)
}
