name: "Run Instrumented Tests"

on:
  pull_request:
    branches:
      - main
      - release/*

jobs:
  run-instrumented-tests:
    name: Run Instrumented Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Set up Gradle
        uses: gradle/gradle-build-action@v3
        with:
          cache-disabled: false

      - name: Run Instrumented Tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 33
          target: google_apis
          arch: arm64-v8a
          profile: pixel_5
          force-avd-creation: true
          emulator-options: -no-window -gpu swiftshader_indirect -no-snapshot -noaudio -no-boot-anim
          disable-animations: true
          emulator-boot-timeout: 900
          script: ./gradlew connectedDebugAndroidTest
